local Rayfield = loadstring(game:HttpGet("https://sirius.menu/rayfield"))()
local Window = Rayfield:CreateWindow({Name = "MM2 Ultimate | Delta",LoadingTitle = "MM2 Ultimate",LoadingSubtitle = "Delta Executor",ConfigurationSaving = {Enabled = false},Discord = {Enabled = false},KeySystem = false})
local Players = game:GetService("Players")
local LocalPlayer = Players.LocalPlayer
local Camera = workspace.CurrentCamera
local CoinEnabled = false
local MurderEnabled = false
local SheriffEnabled = false
local SilentAimEnabled = false
local function getCharacter() return LocalPlayer.Character end
local function getHRP() local char = getCharacter() return char and char:FindFirstChild("HumanoidRootPart") end
local function isAlive(player) local char = player.Character if not char then return false end local hum = char:FindFirstChildOfClass("Humanoid") return hum and hum.Health > 0 end
local CoinTab = Window:CreateTab("Coins", 4483362458)
local function scanCoins() local coins = {} for _, obj in ipairs(workspace:GetDescendants()) do if (obj:IsA("BasePart") or obj:IsA("Part") or obj:IsA("MeshPart")) and obj.Name:lower():find("coin") and obj.Parent then table.insert(coins, obj) end end return coins end
local function getNearestCoin(coins, hrp) local nearest, minDist = nil, math.huge for _, coin in ipairs(coins) do if coin and coin.Parent then local d = (hrp.Position - coin.Position).Magnitude if d < minDist then minDist = d; nearest = coin end end end return nearest end
local function coinLoop() while CoinEnabled do local char = getCharacter() local hrp = getHRP() if char and hrp then local coins = scanCoins() local nearest = getNearestCoin(coins, hrp) if nearest and nearest.Parent then hrp.CFrame = nearest.CFrame + Vector3.new(0, 3, 0) task.wait(0.12) firetouchinterest(hrp, nearest, 0) task.wait(0.08) firetouchinterest(hrp, nearest, 1) end end task.wait(0.25) end end
CoinTab:CreateToggle({Name = "Auto Collect Coins",CurrentValue = false,Flag = "CoinToggle",Callback = function(v) CoinEnabled = v if CoinEnabled then task.spawn(coinLoop) end end})
CoinTab:CreateButton({Name = "Collect All (One-Time)",Callback = function() local hrp = getHRP() if not hrp then return end for _, obj in ipairs(workspace:GetDescendants()) do if (obj:IsA("BasePart") or obj:IsA("Part") or obj:IsA("MeshPart")) and obj.Name:lower():find("coin") and obj.Parent then hrp.CFrame = obj.CFrame + Vector3.new(0, 3, 0) task.wait(0.05) firetouchinterest(hrp, obj, 0) task.wait(0.05) firetouchinterest(hrp, obj, 1) task.wait(0.05) end end end})
local MurderTab = Window:CreateTab("Murder", 4483362458)
local function hasMurdererKnife() local char = getCharacter() if not char then return false end local backpack = LocalPlayer:FindFirstChildOfClass("Backpack") local function checkTools(parent) for _, tool in ipairs(parent:GetChildren()) do if tool:IsA("Tool") then local n = tool.Name:lower() if n:find("knife") or n:find("murder") then return true end end end return false end return checkTools(char) or (backpack and checkTools(backpack)) end
local function equipKnife() local char = getCharacter() local backpack = LocalPlayer:FindFirstChildOfClass("Backpack") if not backpack then return end for _, tool in ipairs(backpack:GetChildren()) do if tool:IsA("Tool") then local n = tool.Name:lower() if n:find("knife") or n:find("murder") then LocalPlayer.Character.Humanoid:EquipTool(tool) return tool end end end for _, tool in ipairs(char:GetChildren()) do if tool:IsA("Tool") then local n = tool.Name:lower() if n:find("knife") or n:find("murder") then return tool end end end end
local function getNearestPlayer(hrp) local nearest, minDist = nil, math.huge for _, p in ipairs(Players:GetPlayers()) do if p ~= LocalPlayer and isAlive(p) then local phrp = p.Character and p.Character:FindFirstChild("HumanoidRootPart") if phrp then local d = (hrp.Position - phrp.Position).Magnitude if d < minDist then minDist = d; nearest = p end end end end return nearest end
local function murderLoop() while MurderEnabled do if hasMurdererKnife() then local hrp = getHRP() if hrp then local target = getNearestPlayer(hrp) if target and target.Character then local tHRP = target.Character:FindFirstChild("HumanoidRootPart") if tHRP then hrp.CFrame = tHRP.CFrame * CFrame.new(0, 0, 2) task.wait(0.1) local knife = equipKnife() if knife then local knifePart = knife:FindFirstChildOfClass("Part") or knife:FindFirstChildOfClass("MeshPart") if knifePart and tHRP then firetouchinterest(knifePart, tHRP, 0) task.wait(0.05) firetouchinterest(knifePart, tHRP, 1) end end end end end end local delay = math.random(50, 120) / 100 task.wait(delay) end end
MurderTab:CreateToggle({Name = "Auto Kill (Murderer Only)",CurrentValue = false,Flag = "MurderToggle",Callback = function(v) MurderEnabled = v if MurderEnabled then task.spawn(murderLoop) end end})
MurderTab:CreateButton({Name = "Kill Nearest Player Now",Callback = function() if not hasMurdererKnife() then Rayfield:Notify({Title = "Murder",Content = "You don't have a knife!",Duration = 3,Image = 4483362458}) return end local hrp = getHRP() if not hrp then return end local target = getNearestPlayer(hrp) if target and target.Character then local tHRP = target.Character:FindFirstChild("HumanoidRootPart") if tHRP then hrp.CFrame = tHRP.CFrame * CFrame.new(0, 0, 2) task.wait(0.1) local knife = equipKnife() if knife then local knifePart = knife:FindFirstChildOfClass("Part") or knife:FindFirstChildOfClass("MeshPart") if knifePart then firetouchinterest(knifePart, tHRP, 0) task.wait(0.05) firetouchinterest(knifePart, tHRP, 1) end end end end end})
local SheriffTab = Window:CreateTab("Sheriff", 4483362458)
local SelectedTarget = "Auto (Nearest)"
local function getMurderer() for _, p in ipairs(Players:GetPlayers()) do if p ~= LocalPlayer and isAlive(p) then local char = p.Character if char then for _, tool in ipairs(char:GetChildren()) do if tool:IsA("Tool") then local n = tool.Name:lower() if n:find("knife") or n:find("murder") then return p end end end end end end end
local ESPHighlights = {}
local function clearESP() for _, h in pairs(ESPHighlights) do if h and h.Parent then h:Destroy() end end ESPHighlights = {} end
local function applyESP(player) if not player or not player.Character then return end local existing = ESPHighlights[player.Name] if existing and existing.Parent then return end local highlight = Instance.new("Highlight") highlight.FillColor = Color3.fromRGB(255, 0, 0) highlight.OutlineColor = Color3.fromRGB(255, 50, 50) highlight.FillTransparency = 0.4 highlight.OutlineTransparency = 0 highlight.Adornee = player.Character highlight.Parent = player.Character ESPHighlights[player.Name] = highlight end
local function getGunTool() local char = getCharacter() local backpack = LocalPlayer:FindFirstChildOfClass("Backpack") local function checkTools(parent) for _, tool in ipairs(parent:GetChildren()) do if tool:IsA("Tool") then local n = tool.Name:lower() if n:find("gun") or n:find("sheriff") or n:find("revolver") or n:find("pistol") then return tool end end end end local t = checkTools(char) if t then return t end if backpack then return checkTools(backpack) end end
local function equipGun() local backpack = LocalPlayer:FindFirstChildOfClass("Backpack") if not backpack then return end for _, tool in ipairs(backpack:GetChildren()) do if tool:IsA("Tool") then local n = tool.Name:lower() if n:find("gun") or n:find("sheriff") or n:find("revolver") or n:find("pistol") then LocalPlayer.Character.Humanoid:EquipTool(tool) return tool end end end return getGunTool() end
local function aimAtHead(targetPlayer) if not targetPlayer or not targetPlayer.Character then return end local head = targetPlayer.Character:FindFirstChild("Head") if not head then return end Camera.CFrame = CFrame.lookAt(Camera.CFrame.Position, head.Position) end
local function sheriffLoop() while SheriffEnabled do local murderer = nil if SelectedTarget == "Auto (Nearest)" then murderer = getMurderer() else murderer = Players:FindFirstChild(SelectedTarget) if not murderer or not isAlive(murderer) then murderer = getMurderer() end end clearESP() if murderer then applyESP(murderer) if SilentAimEnabled then aimAtHead(murderer) end local gun = getGunTool() or equipGun() if gun then local head = murderer.Character and murderer.Character:FindFirstChild("Head") if head then local hrp = getHRP() if hrp then local dist = (hrp.Position - head.Position).Magnitude if dist < 150 then local gunPart = gun:FindFirstChildOfClass("Part") or gun:FindFirstChildOfClass("MeshPart") if gunPart then firetouchinterest(gunPart, head, 0) task.wait(0.05) firetouchinterest(gunPart, head, 1) end end end end end end task.wait(0.5) end clearESP() end
local function getPlayerNames() local names = {"Auto (Nearest)"} for _, p in ipairs(Players:GetPlayers()) do if p ~= LocalPlayer then table.insert(names, p.Name) end end return names end
SheriffTab:CreateToggle({Name = "Auto Shoot Murderer",CurrentValue = false,Flag = "SheriffToggle",Callback = function(v) SheriffEnabled = v if SheriffEnabled then task.spawn(sheriffLoop) end if not SheriffEnabled then clearESP() end end})
SheriffTab:CreateToggle({Name = "Silent Aim (Auto-Aim Head)",CurrentValue = false,Flag = "SilentAimToggle",Callback = function(v) SilentAimEnabled = v end})
SheriffTab:CreateDropdown({Name = "Target Player",Options = getPlayerNames(),CurrentOption = {"Auto (Nearest)"},Flag = "TargetDropdown",Callback = function(selected) SelectedTarget = selected[1] or "Auto (Nearest)" end})
SheriffTab:CreateButton({Name = "Shoot Murderer Now",Callback = function() local murderer = getMurderer() if not murderer then Rayfield:Notify({Title = "Sheriff",Content = "No murderer detected!",Duration = 3,Image = 4483362458}) return end local gun = getGunTool() or equipGun() if not gun then Rayfield:Notify({Title = "Sheriff",Content = "No gun in inventory!",Duration = 3,Image = 4483362458}) return end local head = murderer.Character and murderer.Character:FindFirstChild("Head") if head then aimAtHead(murderer) task.wait(0.1) local gunPart = gun:FindFirstChildOfClass("Part") or gun:FindFirstChildOfClass("MeshPart") if gunPart then firetouch
